eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: studentservice
          uri: http://localhost:9098
          predicates:
            - Path=/students/**
        - id: departmentservice
          uri: http://localhost:9099
          predicates:
            - Path=/department/**
        - id: FacultyService
          uri: http://localhost:8181
          predicates:
            - Path=/faculty/**
        - id: ManagerService
          uri: http://localhost:8082
          predicates:
            - Path=/manager/**
